import { Poppins, Spline_Sans_Mono, Libre_Bodoni } from "next/font/google";
import "@/styles/font.css";

import "@/styles/reset.css";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ScrollProvider } from "@/components/ScrollProvider";
import ViewportHeightHandler from "@/components/ViewportHeightHandler";
import ScrollAnimationsProvider from "@/components/ScrollAnimationsProvider";
import QuickBar from "@/components/layout/quickBar";
import Cursor from "@/components/Cursor";

export const metadata = {
  title: "Advanced Injury & DISC Center",
  description: "Generated by create next app",
};

// 구글 폰트
const poppins = Poppins({
  weight: ["600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});
const splineSansMono = Spline_Sans_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-spline-sans-mono",
});
const libreBodoni = Libre_Bodoni({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre-bodoni",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <ViewportHeightHandler />
        <ScrollProvider>
          <ScrollAnimationsProvider>
            <Header />
            <QuickBar />
            {children}
            <Footer />
          </ScrollAnimationsProvider>
        </ScrollProvider>
        <Cursor />
      </body>
    </html>
  );
}
