import "@/styles/font.css";

import "@/styles/reset.css";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ScrollProvider } from "@/components/ScrollProvider";
import ViewportHeightHandler from "@/components/ViewportHeightHandler";
import ScrollAnimationsProvider from "@/components/ScrollAnimationsProvider";
import QuickLinkList from "@/components/layout/QuickLinkList";

export const metadata = {
  title: "Advanced Injury & DISC Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <ViewportHeightHandler />
        <ScrollProvider>
          <ScrollAnimationsProvider>
            <Header />
            <QuickLinkList />
            {children}
            <Footer />
          </ScrollAnimationsProvider>
        </ScrollProvider>
      </body>
    </html>
  );
}
